services:
  - type: web
    name: votasoft-backend
    env: node
    plan: free
    buildCommand: |
      cd client
      npm install
      npm run build -- --configuration production
      cd ..
      npm install
    startCommand: node server.ts
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - src: /api/(.*)
        dest: /api/$1
      - src: /(.*)
        dest: /client/dist/$1
