[
build
]
     base = "MEAN/client"
     command = "npm run build"
     publish = "dist/client/browser"

   [[
plugins
]]
     package = "@netlify/angular-runtime"

   [
dev
]
     command = "ng serve"
     targetPort = 4200
   